#################################################################################################################
# Create an object store with settings for a test environment. Only a single OSD is required in this example.
#  kubectl create -f object-multisite-pull-realm-test.yaml
#################################################################################################################
apiVersion: v1
kind: Secret
metadata:
  name: realm-a-keys
  namespace: rook-ceph
data:
  # TODO: Replace with keys for your cluster
  # these keys should be the base64 encoded versions of the actual keys or copied from the realm's on the other cluster's secret
  access-key: SXlOM2ZWWk9VMFJXZXoxNlBUaz0=
  secret-key: ZUVCNGVTcExXeUplVmt4UU96c3FYVlplZURaY01TODVWRkZNWVE9PQ==
---
apiVersion: ceph.rook.io/v1
kind: CephObjectRealm
metadata:
  name: realm-a
  namespace: rook-ceph # namespace:cluster
spec:
  # This endpoint in this section needs is an endpoint from the master zone in the master zone group of realm-a. See object-multisite.md for more details.
  # This value must include http(s):// at the beginning
  # ex:
  #   pull:
  #     endpoint: http://10.103.133.16:80
  pull:
    endpoint: "http://192.168.122.211:30028"
---
apiVersion: ceph.rook.io/v1
kind: CephObjectZoneGroup
metadata:
  name: zonegroup-a
  namespace: rook-ceph # namespace:cluster
spec:
  realm: realm-a
---
apiVersion: ceph.rook.io/v1
kind: CephObjectZone
metadata:
  name: zone-b
  namespace: rook-ceph # namespace:cluster
spec:
  zoneGroup: zonegroup-a
  metadataPool:
    failureDomain: host
    replicated:
      size: 1
      requireSafeReplicaSize: false
  dataPool:
    failureDomain: host
    replicated:
      size: 1
      requireSafeReplicaSize: false
    parameters:
      compression_mode: none
  # recommended to set this value if ingress used for exposing rgw endpoints
  customEndpoints:
  - "http://192.168.122.28:30028"
  # if the pools need to be removed from backend enable following setting
  # preservePoolsOnDelete: false
---
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: objectstore
  namespace: rook-ceph # namespace:cluster
spec:
  gateway:
    port: 80
    # securePort: 443
    instances: 1
  zone:
    name: zone-b

